Use latest Azure Storage libraries
HaveIBeenPwned/PwnedPasswordsAzureFunction pull request #33
Opened 2021-06-04 09:55 UTC by rzontar

The function app references the deprecated [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) NuGet package for accessing the Blobs. Although there is a newer version of the library [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/) which provides API parity, it's advice to move to [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs).

As noted in https://github.com/Azure/azure-storage-net/issues/732#issuecomment-745749919 `CloudBlobContainer` is not thread safe, while the new client is.

This change also has a perf benefit. While testing on the local box with storage emulator, i experienced reduced end to end response times:
NuGet | Average | Min | Max | Std. Dev.
-- | -- | -- | -- | --
WindowsAzure.Storage | 110 | 97 | 174 | 14.19
Azure.Storage.Blobs | 53 | 44 | 98 | 8.34

It must be noted that this references a beta package, where the `DownloadStreamingAsync` is implemented. I didn't manage to find a suitable alternative, which would not make 2 round trips to the storage for accessing the properties.

2021-06-04 11:33 UTC, stebet commented
Ahh I had totally missed that the project was using a deprecated packages. Good catch! This might also explain the missing dependency telemetry :)

2021-06-08 17:01 UTC, stebet commented
@rzontar Could you update this PR to use the latest official version even if it uses two roundtrips to the blob storage? Then feel free to submit another PR with the updated version once it is officially released.

2021-06-09 06:20 UTC, rzontar commented
Luckily, a new minor version came out just a few hours ago. Bumped the dependency in the csproj.

2021-06-09 09:12 UTC, stebet requested changes

2021-06-09 09:12 UTC, stebet commented on Functions/Program.cs
> +                        });
```suggestion
                    services.AddAzureClients(azure => azure.AddBlobServiceClient(storageConnectionString));
```

2021-06-09 09:12 UTC, stebet commented on Functions/Program.cs
> +                        });
Think this is cleaner this way while we aren't configuring more things :)

2021-06-09 11:15 UTC, rzontar commented on Functions/Program.cs
> +                        });
agree!

2021-06-09 14:19 UTC, stebet commented
This looks good. Thank you for this :)

2021-06-09 14:19 UTC, merged