An Alternative to "Use latest Azure Storage libraries"
HaveIBeenPwned/PwnedPasswordsAzureFunction pull request #36
Opened 2021-06-04 21:04 UTC by martins-vds

Dependent on #35 

This PR is inspired by #33 and proposes a slightly different implementation.

2021-06-04 21:20 UTC, stebet reviewed
Same review comments as for #35

2021-06-04 21:37 UTC, martins-vds commented
Just integrated changes made for #35

2021-06-08 17:31 UTC, stebet requested changes

2021-06-08 17:31 UTC, stebet commented on Functions/Program.cs
> +                        });
```suggestion
                    services.AddAzureClients(azure => azure.AddBlobServiceClient(storageConnectionString));
```

2021-06-08 17:31 UTC, stebet commented on Functions/BlobStorageOptions.cs
> +    }
```suggestion
    public class BlobStorageOptions : IOptions<BlobStorageOptions>
    {
        public string BlobContainerName { get; set; }
        public BlobStorageOptions Value => this;
    }
```

2021-06-08 17:31 UTC, stebet commented on Functions.Tests/Helpers/TestFunctionDefinition.cs
> +                };
What's the point of this dictionary?

2021-06-09 15:40 UTC, martins-vds commented on Functions.Tests/Helpers/TestFunctionDefinition.cs
> +                };
I made it static

2021-06-09 16:36 UTC, stebet requested changes
A lot of code seems to be out of date from `main`, almost like a rebase went wrong. It might be easier to create a new PR from a fresh `main` fork with the changes instead? I think another rebase + force push might get messy.

2021-06-09 16:36 UTC, stebet commented on .github/dependabot.yml
> +      timezone: "Australia/Brisbane"
This change shouldn't be showing up in the PR as it's already in `main`

2021-06-09 16:36 UTC, stebet commented on .github/workflows/ci-build.yml
> +        path: Functions.Tests/TestResults/test-results.trx
This change shouldn't be showing up in the PR as it's already in `main`

2021-06-09 16:36 UTC, stebet commented on .github/workflows/publish-test-results.yml
> +        reporter: dotnet-trx              # Format of test results
This change shouldn't be showing up in the PR as it's already in `main`

2021-06-09 16:36 UTC, stebet commented on Functions/BlobStorage.cs
>              }
These changes seem out of date with what is already on `main`

2021-06-09 16:36 UTC, stebet commented on Functions/Functions.csproj
> +    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.0.0" />
This seems out of date from what is already on `main`.

2021-06-09 17:45 UTC, martins-vds commented
@stebet I'll close this one, wait for #42 to get merged and then I'll resubmit this PR

2021-06-09 17:45 UTC, closed without merging