An Alternative to "Use latest Azure Storage libraries" #2
HaveIBeenPwned/PwnedPasswordsAzureFunction pull request #43
Opened 2021-06-09 17:50 UTC by martins-vds

Copy of #36 

This PR is inspired by #33 and proposes a slightly different implementation.

2021-06-09 18:13 UTC, stebet commented
@martins-vds This is looking good :) Can you fix the nullable warnings?

2021-06-09 18:16 UTC, stebet requested changes

2021-06-09 18:16 UTC, stebet commented on Functions/BlobStorageOptions.cs
> +}
```suggestion
    public class BlobStorageOptions : IOptions<BlobStorageOptions>
    {
        public string BlobContainerName { get; set; }
        public BlobStorageOptions => this;
    }
}
```

2021-06-09 18:18 UTC, stebet commented on Functions.Tests/RangeTests.cs
> +    public class RangeTests
Can you add a test for `NotFound` as well?

2021-06-10 11:35 UTC, stebet requested changes

2021-06-10 11:35 UTC, stebet commented on Functions/BlobStorage.cs
> +			var blobClient = _blobContainerClient.GetBlobClient(fileName);
```suggestion
            var blobClient = _blobContainerClient.GetBlobClient(fileName);
```

2021-06-10 22:31 UTC, stebet requested changes

2021-06-10 22:31 UTC, stebet commented on Functions/BlobStorageOptions.cs
> +        public BlobStorageOptions => this;
Whoops! Was supposed to be:
```suggestion
        public BlobStorageOptions Value => this;
```

2021-06-10 22:36 UTC, stebet requested changes

2021-06-10 22:36 UTC, stebet commented on Functions/BlobStorageOptions.cs
> +﻿namespace Functions
```suggestion
using Microsoft.Extensions.Options;

﻿namespace Functions
```

2021-06-10 23:26 UTC, stebet commented
@martins-vds Can you rebase this PR on `main`after the latest merges so we can accept it :)

2021-06-11 20:42 UTC, martins-vds commented
> @martins-vds Can you rebase this PR on the latest `main` so we can accept it :)

Done!

2021-06-11 20:49 UTC, merged